name: app
description: "A new Flutter project."

publish_to: 'none' # Prevent accidental publishing

version: 1.0.0+1

environment:
  sdk: ^3.5.4

dependencies:
  flutter:
    sdk: flutter

  fl_chart: ^0.63.0
  http: ^1.3.0  # For API calls
  cupertino_icons: ^1.0.8  # iOS-style icons

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0  # Linting for best practices

flutter:
  uses-material-design: true

  # Assets (Make sure your folder exists)
  assets:
    - assets/logos/
